// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbypZZIaOxc6E1CjXDxD3Q5NUS4bkfuK8',
    appId: '1:434739104808:web:a66630ef2905131461791d',
    messagingSenderId: '434739104808',
    projectId: 'punca-ai',
    authDomain: 'punca-ai.firebaseapp.com',
    storageBucket: 'punca-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSLDoTriBsTY6JHSPFSaP68ss0p3kK_e8',
    appId: '1:434739104808:android:bfc11c719393711661791d',
    messagingSenderId: '434739104808',
    projectId: 'punca-ai',
    storageBucket: 'punca-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCakhTh9FEV-8HVhv7ONd_zcjM-Zzrj0yM',
    appId: '1:434739104808:ios:af7d1b30195d4d7661791d',
    messagingSenderId: '434739104808',
    projectId: 'punca-ai',
    storageBucket: 'punca-ai.firebasestorage.app',
    iosBundleId: 'com.puncaai.puncaAi',
  );
}
